import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Control from "@/components/Control";

export const metadata: Metadata = {
  title: "Web tutorials",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch(`${process.env.NEXT_PUBLIC_JSON_DB_URL}/topics`, { cache: "no-store" });
  const topics: { id: number; title: string; body: string }[] = await res.json();

  return (
    <html lang="ko">
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
